id: 71ddc520-83f3-499e-9a71-b8e7d4aacc3a
# opnrvn-r-149
refId: aws-application-services-sns-encrypted-kms
type: asset
name: >
  SNS topic is not encrypted with AWS KMS key
description: >
  Identifies SNS topics that are not encrypted with an AWS KMS key.
severity: low
enabled: true
sql: >
  SELECT arn as assetid
  FROM ${magpie_schema}.awssnstopic
  WHERE (configuration -> 'attributes' -> 'KmsMasterKeyId' is null);
remediation: >
  Enable encryption with an AWS KMS key on SNS topics that currently have is disabled.
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 1.0.6
