id: ee05eba9-30f6-467d-a202-c10f02bf111a
refId: aws-database-redshift-cluster-maintenancesettings-check
type: asset
name: >
  RedShift cluster does not allow version upgrade
description: >
  This rule identifies RedShift clusters which do not allow version upgrades. Enabling version upgrades helps ensure that the Reshift cluster is running with the latest available major version.
severity: low
enabled: true
sql: >
  SELECT arn as assetid
  FROM ${magpie_schema}.awsredshiftcluster
  WHERE (configuration -> 'allowVersionUpgrade' = 'false');
remediation: >
  Enable version upgrades for RedShift clusters.
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 1.0.6
