id: 2aa03842-b62e-4e17-aad1-112e133d544c
refId: aws-database-redshift-cluster-configuration-check
type: asset
name: >
  RedShift Clusters are not encrypted and have logging disabled
description: >
  This rule checks if RedShift Clusters have encryption and logging enabled.
  The rule is NON_COMPLIANT if both are set to false.
severity: high
enabled: true
sql: >
  SELECT arn as assetid
  FROM ${magpie_schema}.awsredshiftcluster
  WHERE (configuration -> 'encrypted' = 'false')
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 0.2.6
