id: 71ddc520-83f3-499e-9a71-b8e7d4aacc3a
# opnrvn-r-149
refId: aws-application-services-sns-encrypted-kms
type: asset
name: >
  Amazon SNS Topic is not Encrypted with AWS KMS Key
description: >
  This rule checks if Amazon SNS Topic is Encrypted with AWS KMS Key. To be compliant an SNS Topic needs to be encrypted with a KMS Key.
severity: low
enabled: true
sql: >
  SELECT arn as assetid
  FROM ${magpie_schema}.awssnstopic
  WHERE (configuration -> 'attributes' -> 'KmsMasterKeyId' is null);
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 0.2.6
