id: 2aa03842-b62e-4e17-aad1-112e133d544c
refId: aws-database-redshift-cluster-configuration-check
type: asset
name: >
  RedShift cluster is not encrypted and logging is disabled
description: >
  Identifies RedShift clusters which are not encrypted and have logging disabled.
severity: high
enabled: true
sql: >
  SELECT arn as assetid
  FROM ${magpie_schema}.awsredshiftcluster
  WHERE (configuration -> 'encrypted' = 'false')
remediation: >
  Enable encryption and logging for RedShift clusters.
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 1.0.6
