id: 0b46d18b-1da7-4604-bc43-1929afa7579a
# opnrvn-r-97
refId: gcp-compute-ensure-app-engine-applications-enforce-https-connections
type: asset
name: >
  Ensure that App Engine applications enforce HTTPS connections
description: >
  In order to maintain the highest level of security all connections to an application should be secure by default.
manualControl: true
severity: high
enabled: true
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 1.0