id: 75a124e6-1820-4e71-96f0-396b5c4719a5
# opnrvn-r-143
refId: gcp-database-ensure-that-cloud-sql-database-instances-are-configured-with-automated-backups
type: asset
name: >
  Ensure that Cloud SQL database instances are configured with automated backups
description: >
  Backups provide a way to restore a Cloud SQL instance to recover lost data or recover from a problem with that instance.
  Automated backups need to be set for any instance that contains data that should be protected from loss or damage.
  This recommendation is applicable for SQL Server, PostgreSql, MySql generation 1 and MySql generation 2 instances.
severity: high
enabled: true
sql: >
  SELECT acc.assetid
    FROM ${magpie_schema}.gcpsqlinstance acc
   WHERE resourcetype = 'GCP::SQL::Instance'
     AND acc."configuration" -> 'settings' -> 'backupConfiguration' -> 'enabled' IS NULL
      OR acc."configuration" -> 'settings' -> 'backupConfiguration' -> 'enabled' <> 'true'
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 1.0.1