id: f5839d08-f236-49ae-9d8c-c584f79578a8
refId: gcp-database-sql-db-flag-configured
type: asset
name: >
  The "user options" database flag for Cloud SQL, SQL Server instance is configured
description: >
  The user options option specifies global defaults for all users.
  A list of default query processing options is established for the duration of a user's work session.
  The "user options" option allows you to change the default values of the SET options (if the server's default settings are not appropriate).
  A user can override these defaults by using the SET statement. You can configure user options dynamically for new logins. 
  After you change the setting of user options, new login sessions use the new setting; current login sessions are not affected. 
  This recommendation is applicable to SQL Server database instances.
severity: medium
enabled: true
sql: >
  SELECT acc.assetid
    FROM ${magpie_schema}.gcp acc
   WHERE resourcetype = 'GCP::SQL::Instance'
     AND acc."configuration" ->> 'databaseVersion' ILIKE 'SQLSERVER%'
     AND EXISTS (
      SELECT value
        FROM jsonb_array_elements(acc."configuration" -> 'settings' -> 'databaseFlags')
       WHERE value ->> 'name' = 'user options'
     )
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 1.0.1
